### PR TITLE
Please review

### PR DESCRIPTION
**Pull request by aspamers-imqs**
Only index.html, app.ts and some minor changes to the main.go file need to be reviewed. The rest of the files are visual studio project files.

### CODE REVIEW

**Comment by bmharper** [comment]
Step 1 is getting rid of the noise. Remove the MSVC projects and all of that other fluff.

**Comment by aspamers-imqs** [comment]
This was something I was wondering about. These files are generated by the solution and are needed if you want to run it. Won't the solution break if i remove them?

**Comment by JacoBriers** [comment]
You only need to check in Grid.csproj, Grid.sln, web.config, web.Debug.config and web.Release.config files

**Comment by JacoBriers** [comment]
Could you please squash the commits and rebase on latest master? I fixed the issues you identified with the backend.

**Pull request closed without merging**
